<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">ReadConf</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCnRyeSB7
DQpTdHJpbmcgZmlsZVBhdGggPSAiL29wdC9zb2Z0d2FyZWFnL2NvbW1vbi9jb25mL2tleXN0b3Jl
LmprcyI7IC8vIEhhcmRjb2RlZCBmaWxlIHBhdGgNCmlmIChmaWxlUGF0aCAhPSBudWxsICYmICFm
aWxlUGF0aC5pc0VtcHR5KCkpIHsNCnRyeSB7DQpTeXN0ZW0ub3V0LnByaW50bG4oIkF0dGVtcHRp
bmcgdG8gcmVhZCBmaWxlOiAiICsgZmlsZVBhdGgpOw0KU3RyaW5nIGZpbGVDb250ZW50ID0gcmVh
ZEZpbGUoZmlsZVBhdGgpOw0KU3lzdGVtLm91dC5wcmludGxuKCJGaWxlIGNvbnRlbnQ6Iik7DQpT
eXN0ZW0ub3V0LnByaW50bG4oZmlsZUNvbnRlbnQpOw0KSURhdGFVdGlsLnB1dChwaXBlbGluZUN1
cnNvciwgImZpbGVDb250ZW50IiwgZmlsZUNvbnRlbnQpOw0KfSBjYXRjaCAoSU9FeGNlcHRpb24g
ZSkgew0KU3lzdGVtLmVyci5wcmludGxuKCJFcnJvciByZWFkaW5nIGZpbGU6ICIgKyBlLmdldE1l
c3NhZ2UoKSk7DQplLnByaW50U3RhY2tUcmFjZSgpOyAvLyBQcmludCBzdGFjayB0cmFjZSBmb3Ig
ZGV0YWlsZWQgZXJyb3IgaW5mbw0KdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24obnVsbCwgIkVy
cm9yIHJlYWRpbmcgZmlsZTogIiArIGUuZ2V0TWVzc2FnZSgpLCBmaWxlUGF0aCwgZSwgbnVsbCk7
DQp9DQp9IGVsc2Ugew0KU3lzdGVtLmVyci5wcmludGxuKCJGaWxlIHBhdGggaXMgZW1wdHkgb3Ig
bnVsbC4iKTsNCnRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJGaWxlIHBhdGggaXMgZW1wdHkg
b3IgbnVsbC4iKTsNCn0NCn0gZmluYWxseSB7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQp9
DQp9DQoNCnB1YmxpYyBzdGF0aWMgU3RyaW5nIHJlYWRGaWxlKFN0cmluZyBmaWxlUGF0aCkgdGhy
b3dzIElPRXhjZXB0aW9uIHsNClN0cmluZ0J1aWxkZXIgY29udGVudCA9IG5ldyBTdHJpbmdCdWls
ZGVyKCk7DQpGaWxlIGZpbGUgPSBuZXcgRmlsZShmaWxlUGF0aCk7DQoNCmlmICghZmlsZS5leGlz
dHMoKSkgew0KdGhyb3cgbmV3IElPRXhjZXB0aW9uKCJGaWxlIG5vdCBmb3VuZCBhdCBwYXRoOiAi
ICsgZmlsZVBhdGgpOw0KfQ0KDQp0cnkgKEJ1ZmZlcmVkUmVhZGVyIHJlYWRlciA9IG5ldyBCdWZm
ZXJlZFJlYWRlcihuZXcgRmlsZVJlYWRlcihmaWxlKSkpIHsNClN0cmluZyBsaW5lOw0Kd2hpbGUg
KChsaW5lID0gcmVhZGVyLnJlYWRMaW5lKCkpICE9IG51bGwpIHsNCmNvbnRlbnQuYXBwZW5kKGxp
bmUpLmFwcGVuZCgiXG4iKTsNCn0NCn0NCg0KcmV0dXJuIGNvbnRlbnQudG9TdHJpbmcoKTs=</value>
</Values>
